Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,6 +21,10 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         RELEASE_BRANCHES: main
         DRY_RUN: true
+        INITIAL_VERSION: 1.0.1
+    
+    outputs:
+      new_version: ${{ steps.tab_bump.outputs.new_tag }}
 
   package-and-publish-commons:
     runs-on: ubuntu-latest
@@ -39,12 +43,17 @@ jobs:
         VERSION: ${{ steps.tab_bump.outputs.new_tag }}
         
     - name: Pack
-      run: |
-        dotnet pack src/Devsulab.Common/ \
-        --configuration Release \
-        -p:PackageVersion=${VERSION} \
-        -p:RepositoryUrl=https://github.com/${{github.repository_owner}}/DevsubLab.Common \
-        -o packages
+        run: |
+          if [ -z "${{ needs.generate-version.outputs.new_version }}" ]; then
+            echo "PackageVersion is not set. Aborting..."
+            exit 1
+          fi
+          dotnet pack src/Devsulab.Common/ \
+          --configuration Release \
+          -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
+          -p:RepositoryUrl=https://github.com/${{github.repository_owner}}/DevsubLab.Common \
+          -o packages
+
 
     - name: Publish
       run: dotnet nuget push packages/*.nupkg
